"""Type stubs for the compiled extension module."""

from typing import Optional

__version__: str

class SoneError(Exception): ...
class IrError(SoneError): ...
class AssetError(SoneError): ...
class RenderError(SoneError): ...

class Engine:
    def __init__(self, base_dir: Optional[str] = None) -> None: ...
    def register_font(self, name: str, data: bytes) -> None: ...
    def register_font_file(self, name: str, path: str) -> None: ...
    def register_image(self, name: str, data: bytes) -> None: ...
    def has_font(self, name: str) -> bool: ...
    def font_families(self) -> list[str]: ...
    def reset_fonts(self) -> None: ...
    def render(
        self,
        document: str,
        format: str = ...,
        density: Optional[float] = ...,
        quality: float = ...,
        strict: bool = ...,
    ) -> bytes: ...
    def render_pages(
        self,
        document: str,
        format: str = ...,
        density: Optional[float] = ...,
        quality: float = ...,
        strict: bool = ...,
    ) -> list[bytes]: ...
    def dump_layout(self, document: str) -> str: ...
    def dump_metadata(self, document: str, granularity: str = ...) -> str: ...
