/**
 * Backend resolution for Node, Bun and Deno.
 *
 * All three implement Node-API, so all three load the same prebuilt `.node`
 * addon; `binding.cjs` (generated by napi-rs) does the platform lookup and
 * falls back from a local build to the `@sonejs/sone-<triple>` package. Deno
 * additionally needs `--allow-ffi` and a real `node_modules` directory
 * (`--node-modules-dir=auto`).
 *
 * The require is synchronous, which is what lets `Font.has()` and
 * `Font.families()` stay synchronous here. The browser build (`binding.browser.ts`)
 * cannot do that, so it resolves lazily instead.
 */
import { createRequire } from "node:module";

import type { Backend } from "./backend.ts";

let cached: Backend | null = null;

/** The backend, loaded on first use. Throws if no native binary is installed. */
export function backendSync(): Backend {
  if (cached != null) return cached;
  const require = createRequire(import.meta.url);
  const native = require("../binding.cjs");
  cached = {
    Engine: native.Engine,
    version: native.version,
    hasFilesystem: true,
  };
  return cached;
}

export function loadBackend(): Promise<Backend> {
  return Promise.resolve(backendSync());
}

/** Whether `backendSync()` can be called without doing any async work. */
export const isSynchronous = true;
