// GENERATED by tool/generate_nodes.py — do not edit by hand.
//
// Every property is a named constructor argument, the shape a Flutter reader
// expects. The cascade setters in node.dart are unchanged and still work, and
// they remain the way to do the two things named arguments cannot express:
// control the order filters are applied in, and pass an explicit null to a
// decoration colour (a null argument here means "unset", not "use the text
// colour").

import 'dart:convert';

import 'keywords.dart';
import 'node.dart';

/// A vertical container.
class Column extends Node with LayoutProps {
  Column({
    List<Node>? children,
    String? tag,
    AlignContent? alignContent,
    AlignItems? alignItems,
    AlignItems? alignSelf,
    num? aspectRatio,
    BoxSizing? boxSizing,
    TextDirection? direction,
    Display? display,
    num? flex,
    Dim? basis,
    FlexDirection? flexDirection,
    num? grow,
    num? shrink,
    FlexWrap? wrap,
    JustifyContent? justifyContent,
    Overflow? overflow,
    Position? position,
    num? gap,
    num? rowGap,
    num? columnGap,
    Dim? size,
    Dim? width,
    Dim? height,
    Dim? minWidth,
    Dim? minHeight,
    Dim? maxWidth,
    Dim? maxHeight,
    Dim? padding,
    Dim? paddingTop,
    Dim? paddingRight,
    Dim? paddingBottom,
    Dim? paddingLeft,
    Dim? margin,
    Dim? marginTop,
    Dim? marginRight,
    Dim? marginBottom,
    Dim? marginLeft,
    num? borderWidth,
    String? borderColor,
    Dim? top,
    Dim? right,
    Dim? bottom,
    Dim? left,
    Dim? start,
    Dim? end,
    Dim? inset,
    int? gridColumn,
    int? gridColumnSpan,
    int? gridRow,
    int? gridRowSpan,
    PageBreakMode? pageBreak,
    num? translateX,
    num? translateY,
    num? rotate,
    num? scale,
    num? opacity,
    Object? bg,
    List<Object>? backgrounds,
    num? cornerRadius,
    List<num>? cornerRadii,
    num? cornerSmoothing,
    Corner? corner,
    List<String>? shadows,
    num? blur,
    num? brightness,
    num? contrast,
    num? grayscale,
    num? hueRotate,
    num? invert,
    num? saturate,
    num? sepia,
  }) : super('column', children: children) {
    if (tag != null) this.tag(tag);
    if (alignContent != null) this.alignContent(alignContent);
    if (alignItems != null) this.alignItems(alignItems);
    if (alignSelf != null) this.alignSelf(alignSelf);
    if (aspectRatio != null) this.aspectRatio(aspectRatio);
    if (boxSizing != null) this.boxSizing(boxSizing);
    if (direction != null) this.direction(direction);
    if (display != null) this.display(display);
    if (flex != null) this.flex(flex);
    if (basis != null) this.basis(basis);
    if (flexDirection != null) this.flexDirection(flexDirection);
    if (grow != null) this.grow(grow);
    if (shrink != null) this.shrink(shrink);
    if (wrap != null) this.wrap(wrap);
    if (justifyContent != null) this.justifyContent(justifyContent);
    if (overflow != null) this.overflow(overflow);
    if (position != null) this.position(position);
    if (gap != null) this.gap(gap);
    if (rowGap != null) this.rowGap(rowGap);
    if (columnGap != null) this.columnGap(columnGap);
    if (size != null) this.size(size);
    if (width != null) this.width(width);
    if (height != null) this.height(height);
    if (minWidth != null) this.minWidth(minWidth);
    if (minHeight != null) this.minHeight(minHeight);
    if (maxWidth != null) this.maxWidth(maxWidth);
    if (maxHeight != null) this.maxHeight(maxHeight);
    if (padding != null) this.padding(padding);
    if (paddingTop != null) this.paddingTop(paddingTop);
    if (paddingRight != null) this.paddingRight(paddingRight);
    if (paddingBottom != null) this.paddingBottom(paddingBottom);
    if (paddingLeft != null) this.paddingLeft(paddingLeft);
    if (margin != null) this.margin(margin);
    if (marginTop != null) this.marginTop(marginTop);
    if (marginRight != null) this.marginRight(marginRight);
    if (marginBottom != null) this.marginBottom(marginBottom);
    if (marginLeft != null) this.marginLeft(marginLeft);
    if (borderWidth != null) this.borderWidth(borderWidth);
    if (borderColor != null) this.borderColor(borderColor);
    if (top != null) this.top(top);
    if (right != null) this.right(right);
    if (bottom != null) this.bottom(bottom);
    if (left != null) this.left(left);
    if (start != null) this.start(start);
    if (end != null) this.end(end);
    if (inset != null) this.inset(inset);
    if (gridColumn != null) this.gridColumn(gridColumn, gridColumnSpan);
    if (gridRow != null) this.gridRow(gridRow, gridRowSpan);
    if (pageBreak != null) this.pageBreak(pageBreak);
    if (translateX != null) this.translateX(translateX);
    if (translateY != null) this.translateY(translateY);
    if (rotate != null) this.rotate(rotate);
    if (scale != null) this.scale(scale);
    if (opacity != null) this.opacity(opacity);
    if (bg != null) this.bg(bg);
    if (backgrounds != null) this.background(backgrounds);
    if (cornerRadius != null) this.cornerRadius(cornerRadius);
    if (cornerRadii != null) this.cornerRadii(cornerRadii);
    if (cornerSmoothing != null) this.cornerSmoothing(cornerSmoothing);
    if (corner != null) this.corner(corner);
    if (shadows != null) {
      for (final value in shadows) shadow(value);
    }
    if (blur != null) this.blur(blur);
    if (brightness != null) this.brightness(brightness);
    if (contrast != null) this.contrast(contrast);
    if (grayscale != null) this.grayscale(grayscale);
    if (hueRotate != null) this.hueRotate(hueRotate);
    if (invert != null) this.invert(invert);
    if (saturate != null) this.saturate(saturate);
    if (sepia != null) this.sepia(sepia);
  }
}

/// A horizontal container.
class Row extends Node with LayoutProps {
  Row({
    List<Node>? children,
    String? tag,
    AlignContent? alignContent,
    AlignItems? alignItems,
    AlignItems? alignSelf,
    num? aspectRatio,
    BoxSizing? boxSizing,
    TextDirection? direction,
    Display? display,
    num? flex,
    Dim? basis,
    FlexDirection? flexDirection,
    num? grow,
    num? shrink,
    FlexWrap? wrap,
    JustifyContent? justifyContent,
    Overflow? overflow,
    Position? position,
    num? gap,
    num? rowGap,
    num? columnGap,
    Dim? size,
    Dim? width,
    Dim? height,
    Dim? minWidth,
    Dim? minHeight,
    Dim? maxWidth,
    Dim? maxHeight,
    Dim? padding,
    Dim? paddingTop,
    Dim? paddingRight,
    Dim? paddingBottom,
    Dim? paddingLeft,
    Dim? margin,
    Dim? marginTop,
    Dim? marginRight,
    Dim? marginBottom,
    Dim? marginLeft,
    num? borderWidth,
    String? borderColor,
    Dim? top,
    Dim? right,
    Dim? bottom,
    Dim? left,
    Dim? start,
    Dim? end,
    Dim? inset,
    int? gridColumn,
    int? gridColumnSpan,
    int? gridRow,
    int? gridRowSpan,
    PageBreakMode? pageBreak,
    num? translateX,
    num? translateY,
    num? rotate,
    num? scale,
    num? opacity,
    Object? bg,
    List<Object>? backgrounds,
    num? cornerRadius,
    List<num>? cornerRadii,
    num? cornerSmoothing,
    Corner? corner,
    List<String>? shadows,
    num? blur,
    num? brightness,
    num? contrast,
    num? grayscale,
    num? hueRotate,
    num? invert,
    num? saturate,
    num? sepia,
  }) : super('row', children: children) {
    if (tag != null) this.tag(tag);
    if (alignContent != null) this.alignContent(alignContent);
    if (alignItems != null) this.alignItems(alignItems);
    if (alignSelf != null) this.alignSelf(alignSelf);
    if (aspectRatio != null) this.aspectRatio(aspectRatio);
    if (boxSizing != null) this.boxSizing(boxSizing);
    if (direction != null) this.direction(direction);
    if (display != null) this.display(display);
    if (flex != null) this.flex(flex);
    if (basis != null) this.basis(basis);
    if (flexDirection != null) this.flexDirection(flexDirection);
    if (grow != null) this.grow(grow);
    if (shrink != null) this.shrink(shrink);
    if (wrap != null) this.wrap(wrap);
    if (justifyContent != null) this.justifyContent(justifyContent);
    if (overflow != null) this.overflow(overflow);
    if (position != null) this.position(position);
    if (gap != null) this.gap(gap);
    if (rowGap != null) this.rowGap(rowGap);
    if (columnGap != null) this.columnGap(columnGap);
    if (size != null) this.size(size);
    if (width != null) this.width(width);
    if (height != null) this.height(height);
    if (minWidth != null) this.minWidth(minWidth);
    if (minHeight != null) this.minHeight(minHeight);
    if (maxWidth != null) this.maxWidth(maxWidth);
    if (maxHeight != null) this.maxHeight(maxHeight);
    if (padding != null) this.padding(padding);
    if (paddingTop != null) this.paddingTop(paddingTop);
    if (paddingRight != null) this.paddingRight(paddingRight);
    if (paddingBottom != null) this.paddingBottom(paddingBottom);
    if (paddingLeft != null) this.paddingLeft(paddingLeft);
    if (margin != null) this.margin(margin);
    if (marginTop != null) this.marginTop(marginTop);
    if (marginRight != null) this.marginRight(marginRight);
    if (marginBottom != null) this.marginBottom(marginBottom);
    if (marginLeft != null) this.marginLeft(marginLeft);
    if (borderWidth != null) this.borderWidth(borderWidth);
    if (borderColor != null) this.borderColor(borderColor);
    if (top != null) this.top(top);
    if (right != null) this.right(right);
    if (bottom != null) this.bottom(bottom);
    if (left != null) this.left(left);
    if (start != null) this.start(start);
    if (end != null) this.end(end);
    if (inset != null) this.inset(inset);
    if (gridColumn != null) this.gridColumn(gridColumn, gridColumnSpan);
    if (gridRow != null) this.gridRow(gridRow, gridRowSpan);
    if (pageBreak != null) this.pageBreak(pageBreak);
    if (translateX != null) this.translateX(translateX);
    if (translateY != null) this.translateY(translateY);
    if (rotate != null) this.rotate(rotate);
    if (scale != null) this.scale(scale);
    if (opacity != null) this.opacity(opacity);
    if (bg != null) this.bg(bg);
    if (backgrounds != null) this.background(backgrounds);
    if (cornerRadius != null) this.cornerRadius(cornerRadius);
    if (cornerRadii != null) this.cornerRadii(cornerRadii);
    if (cornerSmoothing != null) this.cornerSmoothing(cornerSmoothing);
    if (corner != null) this.corner(corner);
    if (shadows != null) {
      for (final value in shadows) shadow(value);
    }
    if (blur != null) this.blur(blur);
    if (brightness != null) this.brightness(brightness);
    if (contrast != null) this.contrast(contrast);
    if (grayscale != null) this.grayscale(grayscale);
    if (hueRotate != null) this.hueRotate(hueRotate);
    if (invert != null) this.invert(invert);
    if (saturate != null) this.saturate(saturate);
    if (sepia != null) this.sepia(sepia);
  }
}

/// A grid container with row-major auto placement.
class Grid extends Node with LayoutProps {
  Grid({
    List<Node>? children,
    String? tag,
    AlignContent? alignContent,
    AlignItems? alignItems,
    AlignItems? alignSelf,
    num? aspectRatio,
    BoxSizing? boxSizing,
    TextDirection? direction,
    Display? display,
    num? flex,
    Dim? basis,
    FlexDirection? flexDirection,
    num? grow,
    num? shrink,
    FlexWrap? wrap,
    JustifyContent? justifyContent,
    Overflow? overflow,
    Position? position,
    num? gap,
    num? rowGap,
    num? columnGap,
    Dim? size,
    Dim? width,
    Dim? height,
    Dim? minWidth,
    Dim? minHeight,
    Dim? maxWidth,
    Dim? maxHeight,
    Dim? padding,
    Dim? paddingTop,
    Dim? paddingRight,
    Dim? paddingBottom,
    Dim? paddingLeft,
    Dim? margin,
    Dim? marginTop,
    Dim? marginRight,
    Dim? marginBottom,
    Dim? marginLeft,
    num? borderWidth,
    String? borderColor,
    Dim? top,
    Dim? right,
    Dim? bottom,
    Dim? left,
    Dim? start,
    Dim? end,
    Dim? inset,
    int? gridColumn,
    int? gridColumnSpan,
    int? gridRow,
    int? gridRowSpan,
    PageBreakMode? pageBreak,
    num? translateX,
    num? translateY,
    num? rotate,
    num? scale,
    num? opacity,
    Object? bg,
    List<Object>? backgrounds,
    num? cornerRadius,
    List<num>? cornerRadii,
    num? cornerSmoothing,
    Corner? corner,
    List<String>? shadows,
    num? blur,
    num? brightness,
    num? contrast,
    num? grayscale,
    num? hueRotate,
    num? invert,
    num? saturate,
    num? sepia,
    List<Track>? columns,
    List<Track>? rows,
    List<Track>? autoRows,
    List<Track>? autoColumns,
  }) : super('grid', children: children) {
    if (tag != null) this.tag(tag);
    if (alignContent != null) this.alignContent(alignContent);
    if (alignItems != null) this.alignItems(alignItems);
    if (alignSelf != null) this.alignSelf(alignSelf);
    if (aspectRatio != null) this.aspectRatio(aspectRatio);
    if (boxSizing != null) this.boxSizing(boxSizing);
    if (direction != null) this.direction(direction);
    if (display != null) this.display(display);
    if (flex != null) this.flex(flex);
    if (basis != null) this.basis(basis);
    if (flexDirection != null) this.flexDirection(flexDirection);
    if (grow != null) this.grow(grow);
    if (shrink != null) this.shrink(shrink);
    if (wrap != null) this.wrap(wrap);
    if (justifyContent != null) this.justifyContent(justifyContent);
    if (overflow != null) this.overflow(overflow);
    if (position != null) this.position(position);
    if (gap != null) this.gap(gap);
    if (rowGap != null) this.rowGap(rowGap);
    if (columnGap != null) this.columnGap(columnGap);
    if (size != null) this.size(size);
    if (width != null) this.width(width);
    if (height != null) this.height(height);
    if (minWidth != null) this.minWidth(minWidth);
    if (minHeight != null) this.minHeight(minHeight);
    if (maxWidth != null) this.maxWidth(maxWidth);
    if (maxHeight != null) this.maxHeight(maxHeight);
    if (padding != null) this.padding(padding);
    if (paddingTop != null) this.paddingTop(paddingTop);
    if (paddingRight != null) this.paddingRight(paddingRight);
    if (paddingBottom != null) this.paddingBottom(paddingBottom);
    if (paddingLeft != null) this.paddingLeft(paddingLeft);
    if (margin != null) this.margin(margin);
    if (marginTop != null) this.marginTop(marginTop);
    if (marginRight != null) this.marginRight(marginRight);
    if (marginBottom != null) this.marginBottom(marginBottom);
    if (marginLeft != null) this.marginLeft(marginLeft);
    if (borderWidth != null) this.borderWidth(borderWidth);
    if (borderColor != null) this.borderColor(borderColor);
    if (top != null) this.top(top);
    if (right != null) this.right(right);
    if (bottom != null) this.bottom(bottom);
    if (left != null) this.left(left);
    if (start != null) this.start(start);
    if (end != null) this.end(end);
    if (inset != null) this.inset(inset);
    if (gridColumn != null) this.gridColumn(gridColumn, gridColumnSpan);
    if (gridRow != null) this.gridRow(gridRow, gridRowSpan);
    if (pageBreak != null) this.pageBreak(pageBreak);
    if (translateX != null) this.translateX(translateX);
    if (translateY != null) this.translateY(translateY);
    if (rotate != null) this.rotate(rotate);
    if (scale != null) this.scale(scale);
    if (opacity != null) this.opacity(opacity);
    if (bg != null) this.bg(bg);
    if (backgrounds != null) this.background(backgrounds);
    if (cornerRadius != null) this.cornerRadius(cornerRadius);
    if (cornerRadii != null) this.cornerRadii(cornerRadii);
    if (cornerSmoothing != null) this.cornerSmoothing(cornerSmoothing);
    if (corner != null) this.corner(corner);
    if (shadows != null) {
      for (final value in shadows) shadow(value);
    }
    if (blur != null) this.blur(blur);
    if (brightness != null) this.brightness(brightness);
    if (contrast != null) this.contrast(contrast);
    if (grayscale != null) this.grayscale(grayscale);
    if (hueRotate != null) this.hueRotate(hueRotate);
    if (invert != null) this.invert(invert);
    if (saturate != null) this.saturate(saturate);
    if (sepia != null) this.sepia(sepia);
    if (columns != null) this.columns(columns);
    if (rows != null) this.rows(rows);
    if (autoRows != null) this.autoRows(autoRows);
    if (autoColumns != null) this.autoColumns(autoColumns);
  }

  void columns(Iterable<Track> tracks) => set('columns', _tracks(tracks));
  void rows(Iterable<Track> tracks) => set('rows', _tracks(tracks));
  void autoRows(Iterable<Track> tracks) => set('autoRows', _tracks(tracks));
  void autoColumns(Iterable<Track> tracks) =>
      set('autoColumns', _tracks(tracks));

  static List<Object> _tracks(Iterable<Track> tracks) => tracks.map((track) {
        if (track is num) return track;
        if (track is String &&
            (track == 'auto' || RegExp(r'^[\d.]+fr$').hasMatch(track))) {
          return track;
        }
        throw ArgumentError.value(
            track, 'track', 'expected a number, "auto", or an fr value');
      }).toList();
}

/// A table row. Children are [TableCell]s.
class TableRow extends Node with LayoutProps {
  TableRow({
    List<Node>? children,
    String? tag,
    AlignContent? alignContent,
    AlignItems? alignItems,
    AlignItems? alignSelf,
    num? aspectRatio,
    BoxSizing? boxSizing,
    TextDirection? direction,
    Display? display,
    num? flex,
    Dim? basis,
    FlexDirection? flexDirection,
    num? grow,
    num? shrink,
    FlexWrap? wrap,
    JustifyContent? justifyContent,
    Overflow? overflow,
    Position? position,
    num? gap,
    num? rowGap,
    num? columnGap,
    Dim? size,
    Dim? width,
    Dim? height,
    Dim? minWidth,
    Dim? minHeight,
    Dim? maxWidth,
    Dim? maxHeight,
    Dim? padding,
    Dim? paddingTop,
    Dim? paddingRight,
    Dim? paddingBottom,
    Dim? paddingLeft,
    Dim? margin,
    Dim? marginTop,
    Dim? marginRight,
    Dim? marginBottom,
    Dim? marginLeft,
    num? borderWidth,
    String? borderColor,
    Dim? top,
    Dim? right,
    Dim? bottom,
    Dim? left,
    Dim? start,
    Dim? end,
    Dim? inset,
    int? gridColumn,
    int? gridColumnSpan,
    int? gridRow,
    int? gridRowSpan,
    PageBreakMode? pageBreak,
    num? translateX,
    num? translateY,
    num? rotate,
    num? scale,
    num? opacity,
    Object? bg,
    List<Object>? backgrounds,
    num? cornerRadius,
    List<num>? cornerRadii,
    num? cornerSmoothing,
    Corner? corner,
    List<String>? shadows,
    num? blur,
    num? brightness,
    num? contrast,
    num? grayscale,
    num? hueRotate,
    num? invert,
    num? saturate,
    num? sepia,
  }) : super('table-row', children: children) {
    if (tag != null) this.tag(tag);
    if (alignContent != null) this.alignContent(alignContent);
    if (alignItems != null) this.alignItems(alignItems);
    if (alignSelf != null) this.alignSelf(alignSelf);
    if (aspectRatio != null) this.aspectRatio(aspectRatio);
    if (boxSizing != null) this.boxSizing(boxSizing);
    if (direction != null) this.direction(direction);
    if (display != null) this.display(display);
    if (flex != null) this.flex(flex);
    if (basis != null) this.basis(basis);
    if (flexDirection != null) this.flexDirection(flexDirection);
    if (grow != null) this.grow(grow);
    if (shrink != null) this.shrink(shrink);
    if (wrap != null) this.wrap(wrap);
    if (justifyContent != null) this.justifyContent(justifyContent);
    if (overflow != null) this.overflow(overflow);
    if (position != null) this.position(position);
    if (gap != null) this.gap(gap);
    if (rowGap != null) this.rowGap(rowGap);
    if (columnGap != null) this.columnGap(columnGap);
    if (size != null) this.size(size);
    if (width != null) this.width(width);
    if (height != null) this.height(height);
    if (minWidth != null) this.minWidth(minWidth);
    if (minHeight != null) this.minHeight(minHeight);
    if (maxWidth != null) this.maxWidth(maxWidth);
    if (maxHeight != null) this.maxHeight(maxHeight);
    if (padding != null) this.padding(padding);
    if (paddingTop != null) this.paddingTop(paddingTop);
    if (paddingRight != null) this.paddingRight(paddingRight);
    if (paddingBottom != null) this.paddingBottom(paddingBottom);
    if (paddingLeft != null) this.paddingLeft(paddingLeft);
    if (margin != null) this.margin(margin);
    if (marginTop != null) this.marginTop(marginTop);
    if (marginRight != null) this.marginRight(marginRight);
    if (marginBottom != null) this.marginBottom(marginBottom);
    if (marginLeft != null) this.marginLeft(marginLeft);
    if (borderWidth != null) this.borderWidth(borderWidth);
    if (borderColor != null) this.borderColor(borderColor);
    if (top != null) this.top(top);
    if (right != null) this.right(right);
    if (bottom != null) this.bottom(bottom);
    if (left != null) this.left(left);
    if (start != null) this.start(start);
    if (end != null) this.end(end);
    if (inset != null) this.inset(inset);
    if (gridColumn != null) this.gridColumn(gridColumn, gridColumnSpan);
    if (gridRow != null) this.gridRow(gridRow, gridRowSpan);
    if (pageBreak != null) this.pageBreak(pageBreak);
    if (translateX != null) this.translateX(translateX);
    if (translateY != null) this.translateY(translateY);
    if (rotate != null) this.rotate(rotate);
    if (scale != null) this.scale(scale);
    if (opacity != null) this.opacity(opacity);
    if (bg != null) this.bg(bg);
    if (backgrounds != null) this.background(backgrounds);
    if (cornerRadius != null) this.cornerRadius(cornerRadius);
    if (cornerRadii != null) this.cornerRadii(cornerRadii);
    if (cornerSmoothing != null) this.cornerSmoothing(cornerSmoothing);
    if (corner != null) this.corner(corner);
    if (shadows != null) {
      for (final value in shadows) shadow(value);
    }
    if (blur != null) this.blur(blur);
    if (brightness != null) this.brightness(brightness);
    if (contrast != null) this.contrast(contrast);
    if (grayscale != null) this.grayscale(grayscale);
    if (hueRotate != null) this.hueRotate(hueRotate);
    if (invert != null) this.invert(invert);
    if (saturate != null) this.saturate(saturate);
    if (sepia != null) this.sepia(sepia);
  }
}

/// A table cell.
class TableCell extends Node with LayoutProps {
  TableCell({
    List<Node>? children,
    String? tag,
    AlignContent? alignContent,
    AlignItems? alignItems,
    AlignItems? alignSelf,
    num? aspectRatio,
    BoxSizing? boxSizing,
    TextDirection? direction,
    Display? display,
    num? flex,
    Dim? basis,
    FlexDirection? flexDirection,
    num? grow,
    num? shrink,
    FlexWrap? wrap,
    JustifyContent? justifyContent,
    Overflow? overflow,
    Position? position,
    num? gap,
    num? rowGap,
    num? columnGap,
    Dim? size,
    Dim? width,
    Dim? height,
    Dim? minWidth,
    Dim? minHeight,
    Dim? maxWidth,
    Dim? maxHeight,
    Dim? padding,
    Dim? paddingTop,
    Dim? paddingRight,
    Dim? paddingBottom,
    Dim? paddingLeft,
    Dim? margin,
    Dim? marginTop,
    Dim? marginRight,
    Dim? marginBottom,
    Dim? marginLeft,
    num? borderWidth,
    String? borderColor,
    Dim? top,
    Dim? right,
    Dim? bottom,
    Dim? left,
    Dim? start,
    Dim? end,
    Dim? inset,
    int? gridColumn,
    int? gridColumnSpan,
    int? gridRow,
    int? gridRowSpan,
    PageBreakMode? pageBreak,
    num? translateX,
    num? translateY,
    num? rotate,
    num? scale,
    num? opacity,
    Object? bg,
    List<Object>? backgrounds,
    num? cornerRadius,
    List<num>? cornerRadii,
    num? cornerSmoothing,
    Corner? corner,
    List<String>? shadows,
    num? blur,
    num? brightness,
    num? contrast,
    num? grayscale,
    num? hueRotate,
    num? invert,
    num? saturate,
    num? sepia,
    int? colspan,
    int? rowspan,
  }) : super('table-cell', children: children) {
    if (tag != null) this.tag(tag);
    if (alignContent != null) this.alignContent(alignContent);
    if (alignItems != null) this.alignItems(alignItems);
    if (alignSelf != null) this.alignSelf(alignSelf);
    if (aspectRatio != null) this.aspectRatio(aspectRatio);
    if (boxSizing != null) this.boxSizing(boxSizing);
    if (direction != null) this.direction(direction);
    if (display != null) this.display(display);
    if (flex != null) this.flex(flex);
    if (basis != null) this.basis(basis);
    if (flexDirection != null) this.flexDirection(flexDirection);
    if (grow != null) this.grow(grow);
    if (shrink != null) this.shrink(shrink);
    if (wrap != null) this.wrap(wrap);
    if (justifyContent != null) this.justifyContent(justifyContent);
    if (overflow != null) this.overflow(overflow);
    if (position != null) this.position(position);
    if (gap != null) this.gap(gap);
    if (rowGap != null) this.rowGap(rowGap);
    if (columnGap != null) this.columnGap(columnGap);
    if (size != null) this.size(size);
    if (width != null) this.width(width);
    if (height != null) this.height(height);
    if (minWidth != null) this.minWidth(minWidth);
    if (minHeight != null) this.minHeight(minHeight);
    if (maxWidth != null) this.maxWidth(maxWidth);
    if (maxHeight != null) this.maxHeight(maxHeight);
    if (padding != null) this.padding(padding);
    if (paddingTop != null) this.paddingTop(paddingTop);
    if (paddingRight != null) this.paddingRight(paddingRight);
    if (paddingBottom != null) this.paddingBottom(paddingBottom);
    if (paddingLeft != null) this.paddingLeft(paddingLeft);
    if (margin != null) this.margin(margin);
    if (marginTop != null) this.marginTop(marginTop);
    if (marginRight != null) this.marginRight(marginRight);
    if (marginBottom != null) this.marginBottom(marginBottom);
    if (marginLeft != null) this.marginLeft(marginLeft);
    if (borderWidth != null) this.borderWidth(borderWidth);
    if (borderColor != null) this.borderColor(borderColor);
    if (top != null) this.top(top);
    if (right != null) this.right(right);
    if (bottom != null) this.bottom(bottom);
    if (left != null) this.left(left);
    if (start != null) this.start(start);
    if (end != null) this.end(end);
    if (inset != null) this.inset(inset);
    if (gridColumn != null) this.gridColumn(gridColumn, gridColumnSpan);
    if (gridRow != null) this.gridRow(gridRow, gridRowSpan);
    if (pageBreak != null) this.pageBreak(pageBreak);
    if (translateX != null) this.translateX(translateX);
    if (translateY != null) this.translateY(translateY);
    if (rotate != null) this.rotate(rotate);
    if (scale != null) this.scale(scale);
    if (opacity != null) this.opacity(opacity);
    if (bg != null) this.bg(bg);
    if (backgrounds != null) this.background(backgrounds);
    if (cornerRadius != null) this.cornerRadius(cornerRadius);
    if (cornerRadii != null) this.cornerRadii(cornerRadii);
    if (cornerSmoothing != null) this.cornerSmoothing(cornerSmoothing);
    if (corner != null) this.corner(corner);
    if (shadows != null) {
      for (final value in shadows) shadow(value);
    }
    if (blur != null) this.blur(blur);
    if (brightness != null) this.brightness(brightness);
    if (contrast != null) this.contrast(contrast);
    if (grayscale != null) this.grayscale(grayscale);
    if (hueRotate != null) this.hueRotate(hueRotate);
    if (invert != null) this.invert(invert);
    if (saturate != null) this.saturate(saturate);
    if (sepia != null) this.sepia(sepia);
    if (colspan != null) this.colspan(colspan);
    if (rowspan != null) this.rowspan(rowspan);
  }

  void colspan(int value) => set('colspan', value);
  void rowspan(int value) => set('rowspan', value);
}

/// One item in a [Bullets] list.
class ListItem extends Node with LayoutProps {
  ListItem({
    List<Node>? children,
    String? tag,
    AlignContent? alignContent,
    AlignItems? alignItems,
    AlignItems? alignSelf,
    num? aspectRatio,
    BoxSizing? boxSizing,
    TextDirection? direction,
    Display? display,
    num? flex,
    Dim? basis,
    FlexDirection? flexDirection,
    num? grow,
    num? shrink,
    FlexWrap? wrap,
    JustifyContent? justifyContent,
    Overflow? overflow,
    Position? position,
    num? gap,
    num? rowGap,
    num? columnGap,
    Dim? size,
    Dim? width,
    Dim? height,
    Dim? minWidth,
    Dim? minHeight,
    Dim? maxWidth,
    Dim? maxHeight,
    Dim? padding,
    Dim? paddingTop,
    Dim? paddingRight,
    Dim? paddingBottom,
    Dim? paddingLeft,
    Dim? margin,
    Dim? marginTop,
    Dim? marginRight,
    Dim? marginBottom,
    Dim? marginLeft,
    num? borderWidth,
    String? borderColor,
    Dim? top,
    Dim? right,
    Dim? bottom,
    Dim? left,
    Dim? start,
    Dim? end,
    Dim? inset,
    int? gridColumn,
    int? gridColumnSpan,
    int? gridRow,
    int? gridRowSpan,
    PageBreakMode? pageBreak,
    num? translateX,
    num? translateY,
    num? rotate,
    num? scale,
    num? opacity,
    Object? bg,
    List<Object>? backgrounds,
    num? cornerRadius,
    List<num>? cornerRadii,
    num? cornerSmoothing,
    Corner? corner,
    List<String>? shadows,
    num? blur,
    num? brightness,
    num? contrast,
    num? grayscale,
    num? hueRotate,
    num? invert,
    num? saturate,
    num? sepia,
    Node? marker,
  }) : super('list-item', children: children) {
    if (tag != null) this.tag(tag);
    if (alignContent != null) this.alignContent(alignContent);
    if (alignItems != null) this.alignItems(alignItems);
    if (alignSelf != null) this.alignSelf(alignSelf);
    if (aspectRatio != null) this.aspectRatio(aspectRatio);
    if (boxSizing != null) this.boxSizing(boxSizing);
    if (direction != null) this.direction(direction);
    if (display != null) this.display(display);
    if (flex != null) this.flex(flex);
    if (basis != null) this.basis(basis);
    if (flexDirection != null) this.flexDirection(flexDirection);
    if (grow != null) this.grow(grow);
    if (shrink != null) this.shrink(shrink);
    if (wrap != null) this.wrap(wrap);
    if (justifyContent != null) this.justifyContent(justifyContent);
    if (overflow != null) this.overflow(overflow);
    if (position != null) this.position(position);
    if (gap != null) this.gap(gap);
    if (rowGap != null) this.rowGap(rowGap);
    if (columnGap != null) this.columnGap(columnGap);
    if (size != null) this.size(size);
    if (width != null) this.width(width);
    if (height != null) this.height(height);
    if (minWidth != null) this.minWidth(minWidth);
    if (minHeight != null) this.minHeight(minHeight);
    if (maxWidth != null) this.maxWidth(maxWidth);
    if (maxHeight != null) this.maxHeight(maxHeight);
    if (padding != null) this.padding(padding);
    if (paddingTop != null) this.paddingTop(paddingTop);
    if (paddingRight != null) this.paddingRight(paddingRight);
    if (paddingBottom != null) this.paddingBottom(paddingBottom);
    if (paddingLeft != null) this.paddingLeft(paddingLeft);
    if (margin != null) this.margin(margin);
    if (marginTop != null) this.marginTop(marginTop);
    if (marginRight != null) this.marginRight(marginRight);
    if (marginBottom != null) this.marginBottom(marginBottom);
    if (marginLeft != null) this.marginLeft(marginLeft);
    if (borderWidth != null) this.borderWidth(borderWidth);
    if (borderColor != null) this.borderColor(borderColor);
    if (top != null) this.top(top);
    if (right != null) this.right(right);
    if (bottom != null) this.bottom(bottom);
    if (left != null) this.left(left);
    if (start != null) this.start(start);
    if (end != null) this.end(end);
    if (inset != null) this.inset(inset);
    if (gridColumn != null) this.gridColumn(gridColumn, gridColumnSpan);
    if (gridRow != null) this.gridRow(gridRow, gridRowSpan);
    if (pageBreak != null) this.pageBreak(pageBreak);
    if (translateX != null) this.translateX(translateX);
    if (translateY != null) this.translateY(translateY);
    if (rotate != null) this.rotate(rotate);
    if (scale != null) this.scale(scale);
    if (opacity != null) this.opacity(opacity);
    if (bg != null) this.bg(bg);
    if (backgrounds != null) this.background(backgrounds);
    if (cornerRadius != null) this.cornerRadius(cornerRadius);
    if (cornerRadii != null) this.cornerRadii(cornerRadii);
    if (cornerSmoothing != null) this.cornerSmoothing(cornerSmoothing);
    if (corner != null) this.corner(corner);
    if (shadows != null) {
      for (final value in shadows) shadow(value);
    }
    if (blur != null) this.blur(blur);
    if (brightness != null) this.brightness(brightness);
    if (contrast != null) this.contrast(contrast);
    if (grayscale != null) this.grayscale(grayscale);
    if (hueRotate != null) this.hueRotate(hueRotate);
    if (invert != null) this.invert(invert);
    if (saturate != null) this.saturate(saturate);
    if (sepia != null) this.sepia(sepia);
    if (marker != null) this.marker(marker);
  }

  /// Override the list's marker for this item alone.
  void marker(Node value) => set('marker', value.toIr());
}

/// A table. Children are [TableRow]s.
class Table extends Node with LayoutProps {
  Table({
    List<Node>? children,
    String? tag,
    AlignContent? alignContent,
    AlignItems? alignItems,
    AlignItems? alignSelf,
    num? aspectRatio,
    BoxSizing? boxSizing,
    TextDirection? direction,
    Display? display,
    num? flex,
    Dim? basis,
    FlexDirection? flexDirection,
    num? grow,
    num? shrink,
    FlexWrap? wrap,
    JustifyContent? justifyContent,
    Overflow? overflow,
    Position? position,
    num? gap,
    num? rowGap,
    num? columnGap,
    Dim? size,
    Dim? width,
    Dim? height,
    Dim? minWidth,
    Dim? minHeight,
    Dim? maxWidth,
    Dim? maxHeight,
    Dim? padding,
    Dim? paddingTop,
    Dim? paddingRight,
    Dim? paddingBottom,
    Dim? paddingLeft,
    Dim? margin,
    Dim? marginTop,
    Dim? marginRight,
    Dim? marginBottom,
    Dim? marginLeft,
    num? borderWidth,
    String? borderColor,
    Dim? top,
    Dim? right,
    Dim? bottom,
    Dim? left,
    Dim? start,
    Dim? end,
    Dim? inset,
    int? gridColumn,
    int? gridColumnSpan,
    int? gridRow,
    int? gridRowSpan,
    PageBreakMode? pageBreak,
    num? translateX,
    num? translateY,
    num? rotate,
    num? scale,
    num? opacity,
    Object? bg,
    List<Object>? backgrounds,
    num? cornerRadius,
    List<num>? cornerRadii,
    num? cornerSmoothing,
    Corner? corner,
    List<String>? shadows,
    num? blur,
    num? brightness,
    num? contrast,
    num? grayscale,
    num? hueRotate,
    num? invert,
    num? saturate,
    num? sepia,
    num? spacing,
    num? spacingColumn,
  }) : super('table', children: children) {
    if (tag != null) this.tag(tag);
    if (alignContent != null) this.alignContent(alignContent);
    if (alignItems != null) this.alignItems(alignItems);
    if (alignSelf != null) this.alignSelf(alignSelf);
    if (aspectRatio != null) this.aspectRatio(aspectRatio);
    if (boxSizing != null) this.boxSizing(boxSizing);
    if (direction != null) this.direction(direction);
    if (display != null) this.display(display);
    if (flex != null) this.flex(flex);
    if (basis != null) this.basis(basis);
    if (flexDirection != null) this.flexDirection(flexDirection);
    if (grow != null) this.grow(grow);
    if (shrink != null) this.shrink(shrink);
    if (wrap != null) this.wrap(wrap);
    if (justifyContent != null) this.justifyContent(justifyContent);
    if (overflow != null) this.overflow(overflow);
    if (position != null) this.position(position);
    if (gap != null) this.gap(gap);
    if (rowGap != null) this.rowGap(rowGap);
    if (columnGap != null) this.columnGap(columnGap);
    if (size != null) this.size(size);
    if (width != null) this.width(width);
    if (height != null) this.height(height);
    if (minWidth != null) this.minWidth(minWidth);
    if (minHeight != null) this.minHeight(minHeight);
    if (maxWidth != null) this.maxWidth(maxWidth);
    if (maxHeight != null) this.maxHeight(maxHeight);
    if (padding != null) this.padding(padding);
    if (paddingTop != null) this.paddingTop(paddingTop);
    if (paddingRight != null) this.paddingRight(paddingRight);
    if (paddingBottom != null) this.paddingBottom(paddingBottom);
    if (paddingLeft != null) this.paddingLeft(paddingLeft);
    if (margin != null) this.margin(margin);
    if (marginTop != null) this.marginTop(marginTop);
    if (marginRight != null) this.marginRight(marginRight);
    if (marginBottom != null) this.marginBottom(marginBottom);
    if (marginLeft != null) this.marginLeft(marginLeft);
    if (borderWidth != null) this.borderWidth(borderWidth);
    if (borderColor != null) this.borderColor(borderColor);
    if (top != null) this.top(top);
    if (right != null) this.right(right);
    if (bottom != null) this.bottom(bottom);
    if (left != null) this.left(left);
    if (start != null) this.start(start);
    if (end != null) this.end(end);
    if (inset != null) this.inset(inset);
    if (gridColumn != null) this.gridColumn(gridColumn, gridColumnSpan);
    if (gridRow != null) this.gridRow(gridRow, gridRowSpan);
    if (pageBreak != null) this.pageBreak(pageBreak);
    if (translateX != null) this.translateX(translateX);
    if (translateY != null) this.translateY(translateY);
    if (rotate != null) this.rotate(rotate);
    if (scale != null) this.scale(scale);
    if (opacity != null) this.opacity(opacity);
    if (bg != null) this.bg(bg);
    if (backgrounds != null) this.background(backgrounds);
    if (cornerRadius != null) this.cornerRadius(cornerRadius);
    if (cornerRadii != null) this.cornerRadii(cornerRadii);
    if (cornerSmoothing != null) this.cornerSmoothing(cornerSmoothing);
    if (corner != null) this.corner(corner);
    if (shadows != null) {
      for (final value in shadows) shadow(value);
    }
    if (blur != null) this.blur(blur);
    if (brightness != null) this.brightness(brightness);
    if (contrast != null) this.contrast(contrast);
    if (grayscale != null) this.grayscale(grayscale);
    if (hueRotate != null) this.hueRotate(hueRotate);
    if (invert != null) this.invert(invert);
    if (saturate != null) this.saturate(saturate);
    if (sepia != null) this.sepia(sepia);
    if (spacing != null) this.spacing(spacing, spacingColumn);
  }

  /// Row and column spacing. One argument sets both.
  void spacing(num row, [num? column]) =>
      set('spacing', <num>[row, column ?? row]);
}

/// A bulleted or numbered list. Named `Bullets` because `List` is `dart:core`'s.
class Bullets extends Node with LayoutProps {
  Bullets({
    List<Node>? children,
    String? tag,
    AlignContent? alignContent,
    AlignItems? alignItems,
    AlignItems? alignSelf,
    num? aspectRatio,
    BoxSizing? boxSizing,
    TextDirection? direction,
    Display? display,
    num? flex,
    Dim? basis,
    FlexDirection? flexDirection,
    num? grow,
    num? shrink,
    FlexWrap? wrap,
    JustifyContent? justifyContent,
    Overflow? overflow,
    Position? position,
    num? gap,
    num? rowGap,
    num? columnGap,
    Dim? size,
    Dim? width,
    Dim? height,
    Dim? minWidth,
    Dim? minHeight,
    Dim? maxWidth,
    Dim? maxHeight,
    Dim? padding,
    Dim? paddingTop,
    Dim? paddingRight,
    Dim? paddingBottom,
    Dim? paddingLeft,
    Dim? margin,
    Dim? marginTop,
    Dim? marginRight,
    Dim? marginBottom,
    Dim? marginLeft,
    num? borderWidth,
    String? borderColor,
    Dim? top,
    Dim? right,
    Dim? bottom,
    Dim? left,
    Dim? start,
    Dim? end,
    Dim? inset,
    int? gridColumn,
    int? gridColumnSpan,
    int? gridRow,
    int? gridRowSpan,
    PageBreakMode? pageBreak,
    num? translateX,
    num? translateY,
    num? rotate,
    num? scale,
    num? opacity,
    Object? bg,
    List<Object>? backgrounds,
    num? cornerRadius,
    List<num>? cornerRadii,
    num? cornerSmoothing,
    Corner? corner,
    List<String>? shadows,
    num? blur,
    num? brightness,
    num? contrast,
    num? grayscale,
    num? hueRotate,
    num? invert,
    num? saturate,
    num? sepia,
    String? listStyle,
    Node? listStyleNode,
    num? markerGap,
    num? markerOffset,
    int? startIndex,
  }) : super('list', children: children) {
    if (tag != null) this.tag(tag);
    if (alignContent != null) this.alignContent(alignContent);
    if (alignItems != null) this.alignItems(alignItems);
    if (alignSelf != null) this.alignSelf(alignSelf);
    if (aspectRatio != null) this.aspectRatio(aspectRatio);
    if (boxSizing != null) this.boxSizing(boxSizing);
    if (direction != null) this.direction(direction);
    if (display != null) this.display(display);
    if (flex != null) this.flex(flex);
    if (basis != null) this.basis(basis);
    if (flexDirection != null) this.flexDirection(flexDirection);
    if (grow != null) this.grow(grow);
    if (shrink != null) this.shrink(shrink);
    if (wrap != null) this.wrap(wrap);
    if (justifyContent != null) this.justifyContent(justifyContent);
    if (overflow != null) this.overflow(overflow);
    if (position != null) this.position(position);
    if (gap != null) this.gap(gap);
    if (rowGap != null) this.rowGap(rowGap);
    if (columnGap != null) this.columnGap(columnGap);
    if (size != null) this.size(size);
    if (width != null) this.width(width);
    if (height != null) this.height(height);
    if (minWidth != null) this.minWidth(minWidth);
    if (minHeight != null) this.minHeight(minHeight);
    if (maxWidth != null) this.maxWidth(maxWidth);
    if (maxHeight != null) this.maxHeight(maxHeight);
    if (padding != null) this.padding(padding);
    if (paddingTop != null) this.paddingTop(paddingTop);
    if (paddingRight != null) this.paddingRight(paddingRight);
    if (paddingBottom != null) this.paddingBottom(paddingBottom);
    if (paddingLeft != null) this.paddingLeft(paddingLeft);
    if (margin != null) this.margin(margin);
    if (marginTop != null) this.marginTop(marginTop);
    if (marginRight != null) this.marginRight(marginRight);
    if (marginBottom != null) this.marginBottom(marginBottom);
    if (marginLeft != null) this.marginLeft(marginLeft);
    if (borderWidth != null) this.borderWidth(borderWidth);
    if (borderColor != null) this.borderColor(borderColor);
    if (top != null) this.top(top);
    if (right != null) this.right(right);
    if (bottom != null) this.bottom(bottom);
    if (left != null) this.left(left);
    if (start != null) this.start(start);
    if (end != null) this.end(end);
    if (inset != null) this.inset(inset);
    if (gridColumn != null) this.gridColumn(gridColumn, gridColumnSpan);
    if (gridRow != null) this.gridRow(gridRow, gridRowSpan);
    if (pageBreak != null) this.pageBreak(pageBreak);
    if (translateX != null) this.translateX(translateX);
    if (translateY != null) this.translateY(translateY);
    if (rotate != null) this.rotate(rotate);
    if (scale != null) this.scale(scale);
    if (opacity != null) this.opacity(opacity);
    if (bg != null) this.bg(bg);
    if (backgrounds != null) this.background(backgrounds);
    if (cornerRadius != null) this.cornerRadius(cornerRadius);
    if (cornerRadii != null) this.cornerRadii(cornerRadii);
    if (cornerSmoothing != null) this.cornerSmoothing(cornerSmoothing);
    if (corner != null) this.corner(corner);
    if (shadows != null) {
      for (final value in shadows) shadow(value);
    }
    if (blur != null) this.blur(blur);
    if (brightness != null) this.brightness(brightness);
    if (contrast != null) this.contrast(contrast);
    if (grayscale != null) this.grayscale(grayscale);
    if (hueRotate != null) this.hueRotate(hueRotate);
    if (invert != null) this.invert(invert);
    if (saturate != null) this.saturate(saturate);
    if (sepia != null) this.sepia(sepia);
    if (listStyle != null) this.listStyle(listStyle);
    if (listStyleNode != null) this.listStyleNode(listStyleNode);
    if (markerGap != null) this.markerGap(markerGap);
    if (markerOffset != null) this.markerOffset(markerOffset);
    if (startIndex != null) this.startIndex(startIndex);
  }

  /// `disc`, `circle`, `square`, `decimal`, `dash`, `none`, or literal text.
  void listStyle(String value) => set('listStyle', value);

  /// A styled marker node. `{}` in its text is replaced with the item number.
  void listStyleNode(Node marker) => set('listStyle', marker.toIr());

  void markerGap(num value) => set('markerGap', value);
  void markerOffset(num value) => set('markerOffset', value);
  void startIndex(int value) => set('startIndex', value);
}

/// An image. [src] is a path, a URL, `asset:name`, or raw bytes.
class Photo extends Node with LayoutProps {
  Photo(
    Object src, {
    String? tag,
    AlignContent? alignContent,
    AlignItems? alignItems,
    AlignItems? alignSelf,
    num? aspectRatio,
    BoxSizing? boxSizing,
    TextDirection? direction,
    Display? display,
    num? flex,
    Dim? basis,
    FlexDirection? flexDirection,
    num? grow,
    num? shrink,
    FlexWrap? wrap,
    JustifyContent? justifyContent,
    Overflow? overflow,
    Position? position,
    num? gap,
    num? rowGap,
    num? columnGap,
    Dim? size,
    Dim? width,
    Dim? height,
    Dim? minWidth,
    Dim? minHeight,
    Dim? maxWidth,
    Dim? maxHeight,
    Dim? padding,
    Dim? paddingTop,
    Dim? paddingRight,
    Dim? paddingBottom,
    Dim? paddingLeft,
    Dim? margin,
    Dim? marginTop,
    Dim? marginRight,
    Dim? marginBottom,
    Dim? marginLeft,
    num? borderWidth,
    String? borderColor,
    Dim? top,
    Dim? right,
    Dim? bottom,
    Dim? left,
    Dim? start,
    Dim? end,
    Dim? inset,
    int? gridColumn,
    int? gridColumnSpan,
    int? gridRow,
    int? gridRowSpan,
    PageBreakMode? pageBreak,
    num? translateX,
    num? translateY,
    num? rotate,
    num? scale,
    num? opacity,
    Object? bg,
    List<Object>? backgrounds,
    num? cornerRadius,
    List<num>? cornerRadii,
    num? cornerSmoothing,
    Corner? corner,
    List<String>? shadows,
    num? blur,
    num? brightness,
    num? contrast,
    num? grayscale,
    num? hueRotate,
    num? invert,
    num? saturate,
    num? sepia,
    ScaleType? scaleType,
    Object? scaleAlignment,
    bool? preserveAspectRatio,
    bool? flipHorizontal,
    bool? flipVertical,
    String? fill,
    String? clipPath,
  }) : super('photo') {
    set(
        'src',
        src is String
            ? src
            : 'data:application/octet-stream;base64,${base64Encode((src as List).cast<int>())}');
    if (tag != null) this.tag(tag);
    if (alignContent != null) this.alignContent(alignContent);
    if (alignItems != null) this.alignItems(alignItems);
    if (alignSelf != null) this.alignSelf(alignSelf);
    if (aspectRatio != null) this.aspectRatio(aspectRatio);
    if (boxSizing != null) this.boxSizing(boxSizing);
    if (direction != null) this.direction(direction);
    if (display != null) this.display(display);
    if (flex != null) this.flex(flex);
    if (basis != null) this.basis(basis);
    if (flexDirection != null) this.flexDirection(flexDirection);
    if (grow != null) this.grow(grow);
    if (shrink != null) this.shrink(shrink);
    if (wrap != null) this.wrap(wrap);
    if (justifyContent != null) this.justifyContent(justifyContent);
    if (overflow != null) this.overflow(overflow);
    if (position != null) this.position(position);
    if (gap != null) this.gap(gap);
    if (rowGap != null) this.rowGap(rowGap);
    if (columnGap != null) this.columnGap(columnGap);
    if (size != null) this.size(size);
    if (width != null) this.width(width);
    if (height != null) this.height(height);
    if (minWidth != null) this.minWidth(minWidth);
    if (minHeight != null) this.minHeight(minHeight);
    if (maxWidth != null) this.maxWidth(maxWidth);
    if (maxHeight != null) this.maxHeight(maxHeight);
    if (padding != null) this.padding(padding);
    if (paddingTop != null) this.paddingTop(paddingTop);
    if (paddingRight != null) this.paddingRight(paddingRight);
    if (paddingBottom != null) this.paddingBottom(paddingBottom);
    if (paddingLeft != null) this.paddingLeft(paddingLeft);
    if (margin != null) this.margin(margin);
    if (marginTop != null) this.marginTop(marginTop);
    if (marginRight != null) this.marginRight(marginRight);
    if (marginBottom != null) this.marginBottom(marginBottom);
    if (marginLeft != null) this.marginLeft(marginLeft);
    if (borderWidth != null) this.borderWidth(borderWidth);
    if (borderColor != null) this.borderColor(borderColor);
    if (top != null) this.top(top);
    if (right != null) this.right(right);
    if (bottom != null) this.bottom(bottom);
    if (left != null) this.left(left);
    if (start != null) this.start(start);
    if (end != null) this.end(end);
    if (inset != null) this.inset(inset);
    if (gridColumn != null) this.gridColumn(gridColumn, gridColumnSpan);
    if (gridRow != null) this.gridRow(gridRow, gridRowSpan);
    if (pageBreak != null) this.pageBreak(pageBreak);
    if (translateX != null) this.translateX(translateX);
    if (translateY != null) this.translateY(translateY);
    if (rotate != null) this.rotate(rotate);
    if (scale != null) this.scale(scale);
    if (opacity != null) this.opacity(opacity);
    if (bg != null) this.bg(bg);
    if (backgrounds != null) this.background(backgrounds);
    if (cornerRadius != null) this.cornerRadius(cornerRadius);
    if (cornerRadii != null) this.cornerRadii(cornerRadii);
    if (cornerSmoothing != null) this.cornerSmoothing(cornerSmoothing);
    if (corner != null) this.corner(corner);
    if (shadows != null) {
      for (final value in shadows) shadow(value);
    }
    if (blur != null) this.blur(blur);
    if (brightness != null) this.brightness(brightness);
    if (contrast != null) this.contrast(contrast);
    if (grayscale != null) this.grayscale(grayscale);
    if (hueRotate != null) this.hueRotate(hueRotate);
    if (invert != null) this.invert(invert);
    if (saturate != null) this.saturate(saturate);
    if (sepia != null) this.sepia(sepia);
    if (scaleType != null) this.scaleType(scaleType, scaleAlignment);
    if (preserveAspectRatio != null)
      this.preserveAspectRatio(preserveAspectRatio);
    if (flipHorizontal != null) this.flipHorizontal(flipHorizontal);
    if (flipVertical != null) this.flipVertical(flipVertical);
    if (fill != null) this.fill(fill);
    if (clipPath != null) this.clipPath(clipPath);
  }

  static const _alignments = <String, double>{
    'start': 0.0,
    'center': 0.5,
    'end': 1.0,
  };

  /// How the image fills its box. The alignment is 0..1, or one of `'start'`,
  /// `'center'`, `'end'`.
  void scaleType(ScaleType value, [Object? alignment]) {
    set('scaleType', value.value);
    if (alignment == null) return;
    set(
      'scaleAlignment',
      alignment is String
          ? (_alignments[alignment] ??
              (throw ArgumentError.value(alignment, 'alignment')))
          : alignment,
    );
  }

  void preserveAspectRatio([bool value = true]) =>
      set('preserveAspectRatio', value);
  void flipHorizontal([bool value = true]) => set('flipHorizontal', value);
  void flipVertical([bool value = true]) => set('flipVertical', value);

  /// The letterbox colour behind a `contain` image.
  void fill(String color) => set('fill', color);

  /// An SVG path the image is clipped to.
  void clipPath(String path) => set('clipPath', path);
}

/// An SVG path. Named `SvgPath` because `Path` is `dart:ui`'s in Flutter.
class SvgPath extends Node with LayoutProps {
  SvgPath(
    String d, {
    String? tag,
    AlignContent? alignContent,
    AlignItems? alignItems,
    AlignItems? alignSelf,
    num? aspectRatio,
    BoxSizing? boxSizing,
    TextDirection? direction,
    Display? display,
    num? flex,
    Dim? basis,
    FlexDirection? flexDirection,
    num? grow,
    num? shrink,
    FlexWrap? wrap,
    JustifyContent? justifyContent,
    Overflow? overflow,
    Position? position,
    num? gap,
    num? rowGap,
    num? columnGap,
    Dim? size,
    Dim? width,
    Dim? height,
    Dim? minWidth,
    Dim? minHeight,
    Dim? maxWidth,
    Dim? maxHeight,
    Dim? padding,
    Dim? paddingTop,
    Dim? paddingRight,
    Dim? paddingBottom,
    Dim? paddingLeft,
    Dim? margin,
    Dim? marginTop,
    Dim? marginRight,
    Dim? marginBottom,
    Dim? marginLeft,
    num? borderWidth,
    String? borderColor,
    Dim? top,
    Dim? right,
    Dim? bottom,
    Dim? left,
    Dim? start,
    Dim? end,
    Dim? inset,
    int? gridColumn,
    int? gridColumnSpan,
    int? gridRow,
    int? gridRowSpan,
    PageBreakMode? pageBreak,
    num? translateX,
    num? translateY,
    num? rotate,
    num? scale,
    num? opacity,
    Object? bg,
    List<Object>? backgrounds,
    num? cornerRadius,
    List<num>? cornerRadii,
    num? cornerSmoothing,
    Corner? corner,
    List<String>? shadows,
    num? blur,
    num? brightness,
    num? contrast,
    num? grayscale,
    num? hueRotate,
    num? invert,
    num? saturate,
    num? sepia,
    String? stroke,
    num? strokeWidth,
    StrokeCap? strokeLineCap,
    StrokeJoin? strokeLineJoin,
    num? strokeMiterLimit,
    List<num>? strokeDashArray,
    num? strokeDashOffset,
    String? fill,
    num? fillOpacity,
    FillRule? fillRule,
    num? scalePath,
  }) : super('path') {
    set('d', d);
    if (tag != null) this.tag(tag);
    if (alignContent != null) this.alignContent(alignContent);
    if (alignItems != null) this.alignItems(alignItems);
    if (alignSelf != null) this.alignSelf(alignSelf);
    if (aspectRatio != null) this.aspectRatio(aspectRatio);
    if (boxSizing != null) this.boxSizing(boxSizing);
    if (direction != null) this.direction(direction);
    if (display != null) this.display(display);
    if (flex != null) this.flex(flex);
    if (basis != null) this.basis(basis);
    if (flexDirection != null) this.flexDirection(flexDirection);
    if (grow != null) this.grow(grow);
    if (shrink != null) this.shrink(shrink);
    if (wrap != null) this.wrap(wrap);
    if (justifyContent != null) this.justifyContent(justifyContent);
    if (overflow != null) this.overflow(overflow);
    if (position != null) this.position(position);
    if (gap != null) this.gap(gap);
    if (rowGap != null) this.rowGap(rowGap);
    if (columnGap != null) this.columnGap(columnGap);
    if (size != null) this.size(size);
    if (width != null) this.width(width);
    if (height != null) this.height(height);
    if (minWidth != null) this.minWidth(minWidth);
    if (minHeight != null) this.minHeight(minHeight);
    if (maxWidth != null) this.maxWidth(maxWidth);
    if (maxHeight != null) this.maxHeight(maxHeight);
    if (padding != null) this.padding(padding);
    if (paddingTop != null) this.paddingTop(paddingTop);
    if (paddingRight != null) this.paddingRight(paddingRight);
    if (paddingBottom != null) this.paddingBottom(paddingBottom);
    if (paddingLeft != null) this.paddingLeft(paddingLeft);
    if (margin != null) this.margin(margin);
    if (marginTop != null) this.marginTop(marginTop);
    if (marginRight != null) this.marginRight(marginRight);
    if (marginBottom != null) this.marginBottom(marginBottom);
    if (marginLeft != null) this.marginLeft(marginLeft);
    if (borderWidth != null) this.borderWidth(borderWidth);
    if (borderColor != null) this.borderColor(borderColor);
    if (top != null) this.top(top);
    if (right != null) this.right(right);
    if (bottom != null) this.bottom(bottom);
    if (left != null) this.left(left);
    if (start != null) this.start(start);
    if (end != null) this.end(end);
    if (inset != null) this.inset(inset);
    if (gridColumn != null) this.gridColumn(gridColumn, gridColumnSpan);
    if (gridRow != null) this.gridRow(gridRow, gridRowSpan);
    if (pageBreak != null) this.pageBreak(pageBreak);
    if (translateX != null) this.translateX(translateX);
    if (translateY != null) this.translateY(translateY);
    if (rotate != null) this.rotate(rotate);
    if (scale != null) this.scale(scale);
    if (opacity != null) this.opacity(opacity);
    if (bg != null) this.bg(bg);
    if (backgrounds != null) this.background(backgrounds);
    if (cornerRadius != null) this.cornerRadius(cornerRadius);
    if (cornerRadii != null) this.cornerRadii(cornerRadii);
    if (cornerSmoothing != null) this.cornerSmoothing(cornerSmoothing);
    if (corner != null) this.corner(corner);
    if (shadows != null) {
      for (final value in shadows) shadow(value);
    }
    if (blur != null) this.blur(blur);
    if (brightness != null) this.brightness(brightness);
    if (contrast != null) this.contrast(contrast);
    if (grayscale != null) this.grayscale(grayscale);
    if (hueRotate != null) this.hueRotate(hueRotate);
    if (invert != null) this.invert(invert);
    if (saturate != null) this.saturate(saturate);
    if (sepia != null) this.sepia(sepia);
    if (stroke != null) this.stroke(stroke);
    if (strokeWidth != null) this.strokeWidth(strokeWidth);
    if (strokeLineCap != null) this.strokeLineCap(strokeLineCap);
    if (strokeLineJoin != null) this.strokeLineJoin(strokeLineJoin);
    if (strokeMiterLimit != null) this.strokeMiterLimit(strokeMiterLimit);
    if (strokeDashArray != null) this.strokeDashArray(strokeDashArray);
    if (strokeDashOffset != null) this.strokeDashOffset(strokeDashOffset);
    if (fill != null) this.fill(fill);
    if (fillOpacity != null) this.fillOpacity(fillOpacity);
    if (fillRule != null) this.fillRule(fillRule);
    if (scalePath != null) this.scalePath(scalePath);
  }

  void stroke(String color) => set('stroke', color);
  void strokeWidth(num value) => set('strokeWidth', value);
  void strokeLineCap(StrokeCap value) => set('strokeLineCap', value.value);
  void strokeLineJoin(StrokeJoin value) => set('strokeLineJoin', value.value);
  void strokeMiterLimit(num value) => set('strokeMiterLimit', value);
  void strokeDashArray(Iterable<num> values) =>
      set('strokeDashArray', values.toList());
  void strokeDashOffset(num value) => set('strokeDashOffset', value);
  void fill(String color) => set('fill', color);
  void fillOpacity(num value) => set('fillOpacity', value);
  void fillRule(FillRule value) => set('fillRule', value.value);

  /// Scale the path data itself, before layout.
  void scalePath(num value) => set('scalePath', value);
}

/// Clips every child to an SVG path.
class ClipGroup extends Node with LayoutProps {
  ClipGroup(
    String clipPath, {
    List<Node>? children,
    String? tag,
    AlignContent? alignContent,
    AlignItems? alignItems,
    AlignItems? alignSelf,
    num? aspectRatio,
    BoxSizing? boxSizing,
    TextDirection? direction,
    Display? display,
    num? flex,
    Dim? basis,
    FlexDirection? flexDirection,
    num? grow,
    num? shrink,
    FlexWrap? wrap,
    JustifyContent? justifyContent,
    Overflow? overflow,
    Position? position,
    num? gap,
    num? rowGap,
    num? columnGap,
    Dim? size,
    Dim? width,
    Dim? height,
    Dim? minWidth,
    Dim? minHeight,
    Dim? maxWidth,
    Dim? maxHeight,
    Dim? padding,
    Dim? paddingTop,
    Dim? paddingRight,
    Dim? paddingBottom,
    Dim? paddingLeft,
    Dim? margin,
    Dim? marginTop,
    Dim? marginRight,
    Dim? marginBottom,
    Dim? marginLeft,
    num? borderWidth,
    String? borderColor,
    Dim? top,
    Dim? right,
    Dim? bottom,
    Dim? left,
    Dim? start,
    Dim? end,
    Dim? inset,
    int? gridColumn,
    int? gridColumnSpan,
    int? gridRow,
    int? gridRowSpan,
    PageBreakMode? pageBreak,
    num? translateX,
    num? translateY,
    num? rotate,
    num? scale,
    num? opacity,
    Object? bg,
    List<Object>? backgrounds,
    num? cornerRadius,
    List<num>? cornerRadii,
    num? cornerSmoothing,
    Corner? corner,
    List<String>? shadows,
    num? blur,
    num? brightness,
    num? contrast,
    num? grayscale,
    num? hueRotate,
    num? invert,
    num? saturate,
    num? sepia,
  }) : super('clip-group', children: children) {
    set('clipPath', clipPath);
    if (tag != null) this.tag(tag);
    if (alignContent != null) this.alignContent(alignContent);
    if (alignItems != null) this.alignItems(alignItems);
    if (alignSelf != null) this.alignSelf(alignSelf);
    if (aspectRatio != null) this.aspectRatio(aspectRatio);
    if (boxSizing != null) this.boxSizing(boxSizing);
    if (direction != null) this.direction(direction);
    if (display != null) this.display(display);
    if (flex != null) this.flex(flex);
    if (basis != null) this.basis(basis);
    if (flexDirection != null) this.flexDirection(flexDirection);
    if (grow != null) this.grow(grow);
    if (shrink != null) this.shrink(shrink);
    if (wrap != null) this.wrap(wrap);
    if (justifyContent != null) this.justifyContent(justifyContent);
    if (overflow != null) this.overflow(overflow);
    if (position != null) this.position(position);
    if (gap != null) this.gap(gap);
    if (rowGap != null) this.rowGap(rowGap);
    if (columnGap != null) this.columnGap(columnGap);
    if (size != null) this.size(size);
    if (width != null) this.width(width);
    if (height != null) this.height(height);
    if (minWidth != null) this.minWidth(minWidth);
    if (minHeight != null) this.minHeight(minHeight);
    if (maxWidth != null) this.maxWidth(maxWidth);
    if (maxHeight != null) this.maxHeight(maxHeight);
    if (padding != null) this.padding(padding);
    if (paddingTop != null) this.paddingTop(paddingTop);
    if (paddingRight != null) this.paddingRight(paddingRight);
    if (paddingBottom != null) this.paddingBottom(paddingBottom);
    if (paddingLeft != null) this.paddingLeft(paddingLeft);
    if (margin != null) this.margin(margin);
    if (marginTop != null) this.marginTop(marginTop);
    if (marginRight != null) this.marginRight(marginRight);
    if (marginBottom != null) this.marginBottom(marginBottom);
    if (marginLeft != null) this.marginLeft(marginLeft);
    if (borderWidth != null) this.borderWidth(borderWidth);
    if (borderColor != null) this.borderColor(borderColor);
    if (top != null) this.top(top);
    if (right != null) this.right(right);
    if (bottom != null) this.bottom(bottom);
    if (left != null) this.left(left);
    if (start != null) this.start(start);
    if (end != null) this.end(end);
    if (inset != null) this.inset(inset);
    if (gridColumn != null) this.gridColumn(gridColumn, gridColumnSpan);
    if (gridRow != null) this.gridRow(gridRow, gridRowSpan);
    if (pageBreak != null) this.pageBreak(pageBreak);
    if (translateX != null) this.translateX(translateX);
    if (translateY != null) this.translateY(translateY);
    if (rotate != null) this.rotate(rotate);
    if (scale != null) this.scale(scale);
    if (opacity != null) this.opacity(opacity);
    if (bg != null) this.bg(bg);
    if (backgrounds != null) this.background(backgrounds);
    if (cornerRadius != null) this.cornerRadius(cornerRadius);
    if (cornerRadii != null) this.cornerRadii(cornerRadii);
    if (cornerSmoothing != null) this.cornerSmoothing(cornerSmoothing);
    if (corner != null) this.corner(corner);
    if (shadows != null) {
      for (final value in shadows) shadow(value);
    }
    if (blur != null) this.blur(blur);
    if (brightness != null) this.brightness(brightness);
    if (contrast != null) this.contrast(contrast);
    if (grayscale != null) this.grayscale(grayscale);
    if (hueRotate != null) this.hueRotate(hueRotate);
    if (invert != null) this.invert(invert);
    if (saturate != null) this.saturate(saturate);
    if (sepia != null) this.sepia(sepia);
  }
}

/// A styled run inside a [Text].
class Span extends Node with SpanStyleProps {
  Span(
    String text, {
    String? color,
    num? fontSize,
    Object? font,
    FontStyle? style,
    Object? weight,
    num? letterSpacing,
    num? wordSpacing,
    num? underline,
    String? underlineColor,
    num? overline,
    String? overlineColor,
    num? lineThrough,
    String? lineThroughColor,
    String? highlight,
    List<String>? dropShadows,
    String? strokeColor,
    num? strokeWidth,
    num? offsetY,
    TextDirection? textDir,
  }) : super('span') {
    inline.add(text);
    if (color != null) this.color(color);
    if (fontSize != null) this.fontSize(fontSize);
    if (font != null)
      this.set('font', font is Iterable ? font.toList() : [font]);
    if (style != null) this.style(style);
    if (weight != null) this.weight(weight);
    if (letterSpacing != null) this.letterSpacing(letterSpacing);
    if (wordSpacing != null) this.wordSpacing(wordSpacing);
    if (underline != null) this.underline(underline);
    if (underlineColor != null) this.underlineColor(underlineColor);
    if (overline != null) this.overline(overline);
    if (overlineColor != null) this.overlineColor(overlineColor);
    if (lineThrough != null) this.lineThrough(lineThrough);
    if (lineThroughColor != null) this.lineThroughColor(lineThroughColor);
    if (highlight != null) this.highlight(highlight);
    if (dropShadows != null) {
      for (final value in dropShadows) dropShadow(value);
    }
    if (strokeColor != null) this.strokeColor(strokeColor);
    if (strokeWidth != null) this.strokeWidth(strokeWidth);
    if (offsetY != null) this.offsetY(offsetY);
    if (textDir != null) this.textDir(textDir);
  }

  /// The font size. A span has no box, so there is nothing to disambiguate.
  void size(num value) => fontSize(value);

  /// Append raw text.
  void content(String text) => inline.add(text);
}

/// Cascades text styling onto its descendants without drawing a box.
class TextDefault extends Node with SpanStyleProps, TextBlockProps {
  TextDefault({
    List<Node>? children,
    String? color,
    num? fontSize,
    Object? font,
    FontStyle? style,
    Object? weight,
    num? letterSpacing,
    num? wordSpacing,
    num? underline,
    String? underlineColor,
    num? overline,
    String? overlineColor,
    num? lineThrough,
    String? lineThroughColor,
    String? highlight,
    List<String>? dropShadows,
    String? strokeColor,
    num? strokeWidth,
    num? offsetY,
    TextDirection? textDir,
    bool? nowrap,
    bool? wrapText,
    num? maxLines,
    LineBreakMode? lineBreak,
    TextOverflow? textOverflow,
    num? lineHeight,
    TextAlign? align,
    num? indent,
    num? hangingIndent,
    List<num>? tabStops,
    String? tabLeader,
    bool? autofit,
    int? orientation,
    Node? clipImage,
    BaseDirection? baseDir,
    TextWrapMode? textWrap,
  }) : super('text-default', children: children) {
    if (color != null) this.color(color);
    if (fontSize != null) this.fontSize(fontSize);
    if (font != null)
      this.set('font', font is Iterable ? font.toList() : [font]);
    if (style != null) this.style(style);
    if (weight != null) this.weight(weight);
    if (letterSpacing != null) this.letterSpacing(letterSpacing);
    if (wordSpacing != null) this.wordSpacing(wordSpacing);
    if (underline != null) this.underline(underline);
    if (underlineColor != null) this.underlineColor(underlineColor);
    if (overline != null) this.overline(overline);
    if (overlineColor != null) this.overlineColor(overlineColor);
    if (lineThrough != null) this.lineThrough(lineThrough);
    if (lineThroughColor != null) this.lineThroughColor(lineThroughColor);
    if (highlight != null) this.highlight(highlight);
    if (dropShadows != null) {
      for (final value in dropShadows) dropShadow(value);
    }
    if (strokeColor != null) this.strokeColor(strokeColor);
    if (strokeWidth != null) this.strokeWidth(strokeWidth);
    if (offsetY != null) this.offsetY(offsetY);
    if (textDir != null) this.textDir(textDir);
    if (nowrap != null) this.nowrap(nowrap);
    if (wrapText != null) this.wrapText(wrapText);
    if (maxLines != null) this.maxLines(maxLines);
    if (lineBreak != null) this.lineBreak(lineBreak);
    if (textOverflow != null) this.textOverflow(textOverflow);
    if (lineHeight != null) this.lineHeight(lineHeight);
    if (align != null) this.align(align);
    if (indent != null) this.indent(indent);
    if (hangingIndent != null) this.hangingIndent(hangingIndent);
    if (tabStops != null) this.tabStops(tabStops);
    if (tabLeader != null) this.tabLeader(tabLeader);
    if (autofit != null) this.autofit(autofit);
    if (orientation != null) this.orientation(orientation);
    if (clipImage != null) this.clipImage(clipImage);
    if (baseDir != null) this.baseDir(baseDir);
    if (textWrap != null) this.textWrap(textWrap);
  }

  /// The font size cascaded onto descendants.
  void size(num value) => fontSize(value);
}

/// A paragraph. [content] is a String, or a list of Strings and [Span]s.
///
/// `size` is the **font** size here, not the box size — matching the TypeScript
/// API, where `TextPropsBuilder` omits the layout `size`. Use `width` and
/// `height` for the box.
class Text extends Node with LayoutProps, SpanStyleProps, TextBlockProps {
  Text(
    Object? content, {
    String? tag,
    AlignContent? alignContent,
    AlignItems? alignItems,
    AlignItems? alignSelf,
    num? aspectRatio,
    BoxSizing? boxSizing,
    TextDirection? direction,
    Display? display,
    num? flex,
    Dim? basis,
    FlexDirection? flexDirection,
    num? grow,
    num? shrink,
    FlexWrap? wrap,
    JustifyContent? justifyContent,
    Overflow? overflow,
    Position? position,
    num? gap,
    num? rowGap,
    num? columnGap,
    Dim? width,
    Dim? height,
    Dim? minWidth,
    Dim? minHeight,
    Dim? maxWidth,
    Dim? maxHeight,
    Dim? padding,
    Dim? paddingTop,
    Dim? paddingRight,
    Dim? paddingBottom,
    Dim? paddingLeft,
    Dim? margin,
    Dim? marginTop,
    Dim? marginRight,
    Dim? marginBottom,
    Dim? marginLeft,
    num? borderWidth,
    String? borderColor,
    Dim? top,
    Dim? right,
    Dim? bottom,
    Dim? left,
    Dim? start,
    Dim? end,
    Dim? inset,
    int? gridColumn,
    int? gridColumnSpan,
    int? gridRow,
    int? gridRowSpan,
    PageBreakMode? pageBreak,
    num? translateX,
    num? translateY,
    num? rotate,
    num? scale,
    num? opacity,
    Object? bg,
    List<Object>? backgrounds,
    num? cornerRadius,
    List<num>? cornerRadii,
    num? cornerSmoothing,
    Corner? corner,
    List<String>? shadows,
    num? blur,
    num? brightness,
    num? contrast,
    num? grayscale,
    num? hueRotate,
    num? invert,
    num? saturate,
    num? sepia,
    num? size,
    String? color,
    num? fontSize,
    Object? font,
    FontStyle? style,
    Object? weight,
    num? letterSpacing,
    num? wordSpacing,
    num? underline,
    String? underlineColor,
    num? overline,
    String? overlineColor,
    num? lineThrough,
    String? lineThroughColor,
    String? highlight,
    List<String>? dropShadows,
    String? strokeColor,
    num? strokeWidth,
    num? offsetY,
    TextDirection? textDir,
    bool? nowrap,
    bool? wrapText,
    num? maxLines,
    LineBreakMode? lineBreak,
    TextOverflow? textOverflow,
    num? lineHeight,
    TextAlign? align,
    num? indent,
    num? hangingIndent,
    List<num>? tabStops,
    String? tabLeader,
    bool? autofit,
    int? orientation,
    Node? clipImage,
    BaseDirection? baseDir,
    TextWrapMode? textWrap,
  }) : super('text') {
    if (content is String) {
      inline.add(content);
    } else if (content is Iterable) {
      for (final item in content) {
        inline.add(item is Span ? item : item as String);
      }
    } else if (content != null) {
      throw ArgumentError.value(
          content, 'content', 'expected a String or a list');
    }
    if (tag != null) this.tag(tag);
    if (alignContent != null) this.alignContent(alignContent);
    if (alignItems != null) this.alignItems(alignItems);
    if (alignSelf != null) this.alignSelf(alignSelf);
    if (aspectRatio != null) this.aspectRatio(aspectRatio);
    if (boxSizing != null) this.boxSizing(boxSizing);
    if (direction != null) this.direction(direction);
    if (display != null) this.display(display);
    if (flex != null) this.flex(flex);
    if (basis != null) this.basis(basis);
    if (flexDirection != null) this.flexDirection(flexDirection);
    if (grow != null) this.grow(grow);
    if (shrink != null) this.shrink(shrink);
    if (wrap != null) this.wrap(wrap);
    if (justifyContent != null) this.justifyContent(justifyContent);
    if (overflow != null) this.overflow(overflow);
    if (position != null) this.position(position);
    if (gap != null) this.gap(gap);
    if (rowGap != null) this.rowGap(rowGap);
    if (columnGap != null) this.columnGap(columnGap);
    if (width != null) this.width(width);
    if (height != null) this.height(height);
    if (minWidth != null) this.minWidth(minWidth);
    if (minHeight != null) this.minHeight(minHeight);
    if (maxWidth != null) this.maxWidth(maxWidth);
    if (maxHeight != null) this.maxHeight(maxHeight);
    if (padding != null) this.padding(padding);
    if (paddingTop != null) this.paddingTop(paddingTop);
    if (paddingRight != null) this.paddingRight(paddingRight);
    if (paddingBottom != null) this.paddingBottom(paddingBottom);
    if (paddingLeft != null) this.paddingLeft(paddingLeft);
    if (margin != null) this.margin(margin);
    if (marginTop != null) this.marginTop(marginTop);
    if (marginRight != null) this.marginRight(marginRight);
    if (marginBottom != null) this.marginBottom(marginBottom);
    if (marginLeft != null) this.marginLeft(marginLeft);
    if (borderWidth != null) this.borderWidth(borderWidth);
    if (borderColor != null) this.borderColor(borderColor);
    if (top != null) this.top(top);
    if (right != null) this.right(right);
    if (bottom != null) this.bottom(bottom);
    if (left != null) this.left(left);
    if (start != null) this.start(start);
    if (end != null) this.end(end);
    if (inset != null) this.inset(inset);
    if (gridColumn != null) this.gridColumn(gridColumn, gridColumnSpan);
    if (gridRow != null) this.gridRow(gridRow, gridRowSpan);
    if (pageBreak != null) this.pageBreak(pageBreak);
    if (translateX != null) this.translateX(translateX);
    if (translateY != null) this.translateY(translateY);
    if (rotate != null) this.rotate(rotate);
    if (scale != null) this.scale(scale);
    if (opacity != null) this.opacity(opacity);
    if (bg != null) this.bg(bg);
    if (backgrounds != null) this.background(backgrounds);
    if (cornerRadius != null) this.cornerRadius(cornerRadius);
    if (cornerRadii != null) this.cornerRadii(cornerRadii);
    if (cornerSmoothing != null) this.cornerSmoothing(cornerSmoothing);
    if (corner != null) this.corner(corner);
    if (shadows != null) {
      for (final value in shadows) shadow(value);
    }
    if (blur != null) this.blur(blur);
    if (brightness != null) this.brightness(brightness);
    if (contrast != null) this.contrast(contrast);
    if (grayscale != null) this.grayscale(grayscale);
    if (hueRotate != null) this.hueRotate(hueRotate);
    if (invert != null) this.invert(invert);
    if (saturate != null) this.saturate(saturate);
    if (sepia != null) this.sepia(sepia);
    if (size != null) this.size(size);
    if (color != null) this.color(color);
    if (fontSize != null) this.fontSize(fontSize);
    if (font != null)
      this.set('font', font is Iterable ? font.toList() : [font]);
    if (style != null) this.style(style);
    if (weight != null) this.weight(weight);
    if (letterSpacing != null) this.letterSpacing(letterSpacing);
    if (wordSpacing != null) this.wordSpacing(wordSpacing);
    if (underline != null) this.underline(underline);
    if (underlineColor != null) this.underlineColor(underlineColor);
    if (overline != null) this.overline(overline);
    if (overlineColor != null) this.overlineColor(overlineColor);
    if (lineThrough != null) this.lineThrough(lineThrough);
    if (lineThroughColor != null) this.lineThroughColor(lineThroughColor);
    if (highlight != null) this.highlight(highlight);
    if (dropShadows != null) {
      for (final value in dropShadows) dropShadow(value);
    }
    if (strokeColor != null) this.strokeColor(strokeColor);
    if (strokeWidth != null) this.strokeWidth(strokeWidth);
    if (offsetY != null) this.offsetY(offsetY);
    if (textDir != null) this.textDir(textDir);
    if (nowrap != null) this.nowrap(nowrap);
    if (wrapText != null) this.wrapText(wrapText);
    if (maxLines != null) this.maxLines(maxLines);
    if (lineBreak != null) this.lineBreak(lineBreak);
    if (textOverflow != null) this.textOverflow(textOverflow);
    if (lineHeight != null) this.lineHeight(lineHeight);
    if (align != null) this.align(align);
    if (indent != null) this.indent(indent);
    if (hangingIndent != null) this.hangingIndent(hangingIndent);
    if (tabStops != null) this.tabStops(tabStops);
    if (tabLeader != null) this.tabLeader(tabLeader);
    if (autofit != null) this.autofit(autofit);
    if (orientation != null) this.orientation(orientation);
    if (clipImage != null) this.clipImage(clipImage);
    if (baseDir != null) this.baseDir(baseDir);
    if (textWrap != null) this.textWrap(textWrap);
  }

  /// The **font** size, not the box size. Both included mixins would otherwise
  /// resolve `size` to the layout one, and the `size:` named argument calls
  /// straight through here — so this override is what keeps the two honest.
  @override
  void size(Object value, [Object? height]) {
    if (height != null) {
      throw ArgumentError.value(height, 'height',
          'Text.size is the font size; use width and height for the box');
    }
    if (value is! num) {
      throw ArgumentError.value(
          value, 'size', 'expected a font size in points');
    }
    fontSize(value);
  }

  /// Append raw text.
  void content(String text) => inline.add(text);

  /// Append a styled run.
  void span(Span run) => inline.add(run);
}

/// An explicit page break. Only meaningful with `pageHeight` set.
Column pageBreak() => Column(height: 0, pageBreak: PageBreakMode.before);
